using CsvViewer.Services;
using CsvViewer.ViewModels;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace CsvViewer;

public partial class CsvDocumentGrid : UserControl
{
    private readonly ClipboardService _clipboardService = new();
    private readonly List<DataGridColumn> _widthObservedColumns = [];
    private readonly Style _searchHighlightTextStyle;
    private bool _syncingHorizontalScroll;
    private bool _syncingColumnWidths;
    private bool _columnLayoutSyncQueued;

    public CsvDocumentGrid()
    {
        InitializeComponent();
        _searchHighlightTextStyle = CreateSearchHighlightTextStyle();
        DataContextChanged += CsvDocumentGrid_DataContextChanged;
    }

    public void CopySelectedCells()
    {
        _clipboardService.CopySelectedCells(FrozenRowsDataGrid.IsKeyboardFocusWithin ? FrozenRowsDataGrid : CsvDataGrid);
    }

    public bool FreezeToCurrentCell()
    {
        var rowCount = GetCurrentCellRowFreezeCount();
        var columnCount = GetCurrentCellColumnFreezeCount();
        if (rowCount == 0 || columnCount == 0)
        {
            return false;
        }

        if (DataContext is CsvDocumentViewModel document)
        {
            document.SetFrozenRowCount(rowCount);
            document.FrozenColumnCount = columnCount;
        }

        ApplyFrozenColumnCount(columnCount);
        return true;
    }

    public void ClearFreeze()
    {
        if (DataContext is CsvDocumentViewModel document)
        {
            document.SetFrozenRowCount(0);
            document.FrozenColumnCount = 0;
        }

        ApplyFrozenColumnCount(0);
    }

    public void ApplyDocumentFrozenState()
    {
        ApplyFrozenColumnCount(GetFrozenColumnCount());
    }

    private void CsvDocumentGrid_DataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        ApplyDocumentFrozenState();
        QueueColumnLayoutSync();
    }

    private void CsvDataGrid_LoadingRow(object? sender, DataGridRowEventArgs e)
    {
        e.Row.Header = e.Row.GetIndex() + GetFrozenRowCount() + 1;
    }

    private void FrozenRowsDataGrid_LoadingRow(object? sender, DataGridRowEventArgs e)
    {
        e.Row.Header = e.Row.GetIndex() + 1;
    }

    private void DataGrid_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (e.Column is DataGridTextColumn textColumn)
        {
            textColumn.ElementStyle = _searchHighlightTextStyle;
        }
    }

    private void CsvDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        ApplyDocumentFrozenState();
        RegisterColumnWidthSync();
        QueueColumnLayoutSync();
    }

    private void FrozenRowsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        ApplyDocumentFrozenState();
        RegisterColumnWidthSync();
        QueueColumnLayoutSync();
    }

    private int GetFrozenRowCount()
    {
        return DataContext is CsvDocumentViewModel document ? document.FrozenRowCount : 0;
    }

    private int GetFrozenColumnCount()
    {
        return DataContext is CsvDocumentViewModel document ? document.FrozenColumnCount : 0;
    }

    private void ApplyFrozenColumnCount(int count)
    {
        SetFrozenColumnCount(CsvDataGrid, count);
        SetFrozenColumnCount(FrozenRowsDataGrid, count);
    }

    private static void SetFrozenColumnCount(DataGrid dataGrid, int count)
    {
        var frozenColumnCount = Math.Clamp(count, 0, dataGrid.Columns.Count);
        if (dataGrid.FrozenColumnCount != frozenColumnCount)
        {
            dataGrid.FrozenColumnCount = frozenColumnCount;
        }
    }

    private int GetCurrentCellRowFreezeCount()
    {
        if (TryGetActiveCell(out var dataGrid, out _, out var item))
        {
            var rowIndex = dataGrid.Items.IndexOf(item);
            if (rowIndex < 0)
            {
                return 0;
            }

            return dataGrid == FrozenRowsDataGrid ? rowIndex + 1 : GetFrozenRowCount() + rowIndex + 1;
        }

        return 0;
    }

    private int GetCurrentCellColumnFreezeCount()
    {
        return TryGetActiveCell(out _, out var column, out _) ? column.DisplayIndex + 1 : 0;
    }

    private bool TryGetActiveCell(out DataGrid dataGrid, out DataGridColumn column, out object item)
    {
        if (FrozenRowsDataGrid.IsKeyboardFocusWithin && TryGetCurrentCell(FrozenRowsDataGrid, out column!, out item!))
        {
            dataGrid = FrozenRowsDataGrid;
            return true;
        }

        if (CsvDataGrid.IsKeyboardFocusWithin && TryGetCurrentCell(CsvDataGrid, out column!, out item!))
        {
            dataGrid = CsvDataGrid;
            return true;
        }

        if (TryGetCurrentCell(FrozenRowsDataGrid, out column!, out item!))
        {
            dataGrid = FrozenRowsDataGrid;
            return true;
        }

        if (TryGetCurrentCell(CsvDataGrid, out column!, out item!))
        {
            dataGrid = CsvDataGrid;
            return true;
        }

        dataGrid = CsvDataGrid;
        column = null!;
        item = null!;
        return false;
    }

    private static bool TryGetCurrentCell(DataGrid dataGrid, out DataGridColumn column, out object item)
    {
        if (dataGrid.SelectedCells.Count > 0)
        {
            var selectedCell = dataGrid.SelectedCells[0];
            if (selectedCell.Column != null && selectedCell.Item != null)
            {
                column = selectedCell.Column;
                item = selectedCell.Item;
                return true;
            }
        }

        if (dataGrid.CurrentColumn != null && dataGrid.CurrentItem != null)
        {
            column = dataGrid.CurrentColumn;
            item = dataGrid.CurrentItem;
            return true;
        }

        column = null!;
        item = null!;
        return false;
    }

    private void CsvDataGrid_ScrollChanged(object sender, ScrollChangedEventArgs e)
    {
        SyncHorizontalScroll(FrozenRowsDataGrid, e.HorizontalOffset, e.HorizontalChange);
    }

    private void CsvDataGrid_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
    {
        if ((Keyboard.Modifiers & ModifierKeys.Shift) != ModifierKeys.Shift)
        {
            return;
        }

        var scrollViewer = FindVisualChild<ScrollViewer>(CsvDataGrid);
        if (scrollViewer == null)
        {
            return;
        }

        scrollViewer.ScrollToHorizontalOffset(scrollViewer.HorizontalOffset - e.Delta);
        e.Handled = true;
    }

    private void FrozenRowsDataGrid_ScrollChanged(object sender, ScrollChangedEventArgs e)
    {
        SyncHorizontalScroll(CsvDataGrid, e.HorizontalOffset, e.HorizontalChange);
    }

    private void RegisterColumnWidthSync()
    {
        var descriptor = DependencyPropertyDescriptor.FromProperty(DataGridColumn.ActualWidthProperty, typeof(DataGridColumn));
        foreach (var column in _widthObservedColumns)
        {
            descriptor.RemoveValueChanged(column, MainColumnWidthChanged);
        }

        _widthObservedColumns.Clear();

        if (CsvDataGrid.Columns.Count == 0 || FrozenRowsDataGrid.Columns.Count == 0)
        {
            return;
        }

        foreach (var column in CsvDataGrid.Columns)
        {
            descriptor.AddValueChanged(column, MainColumnWidthChanged);
            _widthObservedColumns.Add(column);
        }
    }

    private void MainColumnWidthChanged(object? sender, EventArgs e)
    {
        if (_syncingColumnWidths)
        {
            return;
        }

        QueueColumnLayoutSync();
    }

    private void QueueColumnLayoutSync()
    {
        if (_columnLayoutSyncQueued)
        {
            return;
        }

        _columnLayoutSyncQueued = true;
        Dispatcher.BeginInvoke(() =>
        {
            _columnLayoutSyncQueued = false;
            SyncColumnLayouts(CsvDataGrid, FrozenRowsDataGrid);
        }, System.Windows.Threading.DispatcherPriority.ContextIdle);
    }

    private Style CreateSearchHighlightTextStyle()
    {
        var style = new Style(typeof(TextBlock));
        style.Setters.Add(new Setter(TextBlock.PaddingProperty, new Thickness(2, 0, 2, 0)));

        if (FindResource("SearchHighlightBrushConverter") is IMultiValueConverter converter)
        {
            var backgroundBinding = new MultiBinding { Converter = converter };
            backgroundBinding.Bindings.Add(new Binding(nameof(TextBlock.Text))
            {
                RelativeSource = new RelativeSource(RelativeSourceMode.Self),
                Mode = BindingMode.OneWay
            });
            backgroundBinding.Bindings.Add(new Binding("DataContext.SearchText")
            {
                RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(CsvDocumentGrid), 1),
                Mode = BindingMode.OneWay
            });

            style.Setters.Add(new Setter(TextBlock.BackgroundProperty, backgroundBinding));
        }

        return style;
    }

    private void SyncHorizontalScroll(DataGrid target, double offset, double change)
    {
        if (_syncingHorizontalScroll || change == 0)
        {
            return;
        }

        var scrollViewer = FindVisualChild<ScrollViewer>(target);
        if (scrollViewer == null)
        {
            return;
        }

        _syncingHorizontalScroll = true;
        scrollViewer.ScrollToHorizontalOffset(offset);
        _syncingHorizontalScroll = false;
    }

    private void SyncColumnLayouts(DataGrid source, DataGrid target)
    {
        if (source.Columns.Count == 0 || target.Columns.Count == 0)
        {
            return;
        }

        try
        {
            _syncingColumnWidths = true;
            var count = Math.Min(source.Columns.Count, target.Columns.Count);
            for (var i = 0; i < count; i++)
            {
                if (target.Columns[i].DisplayIndex != source.Columns[i].DisplayIndex)
                {
                    target.Columns[i].DisplayIndex = source.Columns[i].DisplayIndex;
                }

                var actualWidth = source.Columns[i].ActualWidth;
                if (!double.IsNaN(actualWidth) && actualWidth > 0 && Math.Abs(target.Columns[i].ActualWidth - actualWidth) > 0.5)
                {
                    target.Columns[i].Width = new DataGridLength(actualWidth);
                }
            }
        }
        finally
        {
            _syncingColumnWidths = false;
        }
    }

    private static T? FindVisualChild<T>(DependencyObject parent) where T : DependencyObject
    {
        for (var i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T typedChild)
            {
                return typedChild;
            }

            var descendant = FindVisualChild<T>(child);
            if (descendant != null)
            {
                return descendant;
            }
        }

        return null;
    }
}
