using CsvViewer.Models;
using CsvViewer.Services;
using CsvViewer.ViewModels;
using System.ComponentModel;
using System.Linq;
using System.Windows.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace CsvViewer;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
    private readonly ClipboardService _clipboardService = new();
    private readonly List<DataGridColumn> _widthObservedColumns = [];
    private bool _syncingHorizontalScroll;
    private bool _syncingColumnWidths;

    public MainWindow()
    {
        InitializeComponent();
    }

    private async void Window_Loaded(object sender, RoutedEventArgs e)
    {
        if (DataContext is MainViewModel viewModel)
        {
            await viewModel.InitializeAsync();
        }
    }

    private void CsvDataGrid_LoadingRow(object? sender, DataGridRowEventArgs e)
    {
        e.Row.Header = e.Row.GetIndex() + GetFrozenRowCount() + 1;
    }

    private void FrozenRowsDataGrid_LoadingRow(object? sender, DataGridRowEventArgs e)
    {
        e.Row.Header = e.Row.GetIndex() + 1;
    }

    private void CsvDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        ApplySearchHighlightStyles(CsvDataGrid);
        ApplyFrozenColumnCount(GetFrozenColumnCount());
        RegisterColumnWidthSync();
        QueueColumnLayoutSync();
    }

    private void FrozenRowsDataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        ApplySearchHighlightStyles(FrozenRowsDataGrid);
        ApplyFrozenColumnCount(GetFrozenColumnCount());
        RegisterColumnWidthSync();
        QueueColumnLayoutSync();
    }

    private void Window_DragOver(object sender, DragEventArgs e)
    {
        e.Effects = e.Data.GetDataPresent(DataFormats.FileDrop) ? DragDropEffects.Copy : DragDropEffects.None;
        e.Handled = true;
    }

    private async void Window_Drop(object sender, DragEventArgs e)
    {
        if (DataContext is not MainViewModel viewModel || !e.Data.GetDataPresent(DataFormats.FileDrop))
        {
            return;
        }

        if (e.Data.GetData(DataFormats.FileDrop) is string[] files && files.Length > 0)
        {
            await viewModel.LoadFilesAsync(files);
        }
    }

    private void CopySelected_Click(object sender, RoutedEventArgs e)
    {
        _clipboardService.CopySelectedCells(FrozenRowsDataGrid.IsKeyboardFocusWithin ? FrozenRowsDataGrid : CsvDataGrid);
    }

    private void ClearFreeze_Click(object sender, RoutedEventArgs e)
    {
        ApplyFrozenColumnCount(0);
        ApplyFrozenRowCount(0);
    }

    private void Settings_Click(object sender, RoutedEventArgs e)
    {
        if (DataContext is not MainViewModel viewModel)
        {
            return;
        }

        var settingsWindow = new SettingsWindow
        {
            Owner = this,
            DataContext = viewModel
        };
        settingsWindow.ShowDialog();
    }

    private void FreezeToCurrentCell_Click(object sender, RoutedEventArgs e)
    {
        var rowCount = GetCurrentCellRowFreezeCount();
        var columnCount = GetCurrentCellColumnFreezeCount();
        if (rowCount == 0 || columnCount == 0)
        {
            MessageBox.Show("请先选中要冻结到的单元格。", "冻结窗口", MessageBoxButton.OK, MessageBoxImage.Information);
            return;
        }

        ApplyFrozenRowCount(rowCount);
        ApplyFrozenColumnCount(columnCount);
    }

    private void ApplyFrozenColumnCount(int count)
    {
        var maxCount = Math.Max(CsvDataGrid.Columns.Count, FrozenRowsDataGrid.Columns.Count);
        if (maxCount == 0)
        {
            CsvDataGrid.FrozenColumnCount = 0;
            FrozenRowsDataGrid.FrozenColumnCount = 0;
            UpdateFreezeStatusText();
            return;
        }

        var frozenColumnCount = Math.Clamp(count, 0, maxCount);
        if (DataContext is MainViewModel viewModel)
        {
            viewModel.SetSelectedFrozenColumnCount(frozenColumnCount);
        }

        CsvDataGrid.FrozenColumnCount = Math.Clamp(frozenColumnCount, 0, CsvDataGrid.Columns.Count);
        FrozenRowsDataGrid.FrozenColumnCount = Math.Clamp(frozenColumnCount, 0, FrozenRowsDataGrid.Columns.Count);
        UpdateFreezeStatusText();
    }

    private void ApplyFrozenRowCount(int count)
    {
        if (DataContext is MainViewModel viewModel)
        {
            viewModel.SetSelectedFrozenRowCount(count);
            UpdateFreezeStatusText();
        }
    }

    private int GetFrozenRowCount()
    {
        return DataContext is MainViewModel viewModel ? viewModel.SelectedDocument?.FrozenRowCount ?? 0 : 0;
    }

    private int GetFrozenColumnCount()
    {
        return DataContext is MainViewModel viewModel ? viewModel.SelectedDocument?.FrozenColumnCount ?? 0 : 0;
    }

    private int GetCurrentCellRowFreezeCount()
    {
        if (TryGetActiveCell(out var dataGrid, out _, out var item))
        {
            var rowIndex = dataGrid.Items.IndexOf(item);
            if (rowIndex < 0)
            {
                return 0;
            }

            return dataGrid == FrozenRowsDataGrid ? rowIndex + 1 : GetFrozenRowCount() + rowIndex + 1;
        }

        return 0;
    }

    private int GetCurrentCellColumnFreezeCount()
    {
        return TryGetActiveCell(out _, out var column, out _) ? column.DisplayIndex + 1 : 0;
    }

    private bool TryGetActiveCell(out DataGrid dataGrid, out DataGridColumn column, out object item)
    {
        if (TryGetCurrentCell(FrozenRowsDataGrid, out column!, out item!))
        {
            dataGrid = FrozenRowsDataGrid;
            return true;
        }

        if (TryGetCurrentCell(CsvDataGrid, out column!, out item!))
        {
            dataGrid = CsvDataGrid;
            return true;
        }

        dataGrid = CsvDataGrid;
        column = null!;
        item = null!;
        return false;
    }

    private static bool TryGetCurrentCell(DataGrid dataGrid, out DataGridColumn column, out object item)
    {
        if (dataGrid.SelectedCells.Count > 0)
        {
            var selectedCell = dataGrid.SelectedCells[0];
            if (selectedCell.Column != null && selectedCell.Item != null)
            {
                column = selectedCell.Column;
                item = selectedCell.Item;
                return true;
            }
        }

        if (dataGrid.CurrentColumn != null && dataGrid.CurrentItem != null)
        {
            column = dataGrid.CurrentColumn;
            item = dataGrid.CurrentItem;
            return true;
        }

        column = null!;
        item = null!;
        return false;
    }

    private void UpdateFreezeStatusText()
    {
        var rowCount = GetFrozenRowCount();
        var columnCount = GetFrozenColumnCount();
        if (columnCount == 0 && rowCount == 0)
        {
            FreezeStatusText.Text = "冻结: 无";
            return;
        }

        var parts = new List<string>();
        if (rowCount > 0)
        {
            parts.Add($"前 {rowCount} 行");
        }

        if (columnCount > 0)
        {
            parts.Add($"前 {columnCount} 列");
        }

        FreezeStatusText.Text = $"冻结: {string.Join("，", parts)}";
    }

    private void DocumentTabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (e.Source != DocumentTabControl)
        {
            return;
        }

        Dispatcher.BeginInvoke(() =>
        {
            ApplyFrozenColumnCount(GetFrozenColumnCount());
            UpdateFreezeStatusText();
            QueueColumnLayoutSync();
        }, System.Windows.Threading.DispatcherPriority.Loaded);
    }

    private void CsvDataGrid_ScrollChanged(object sender, ScrollChangedEventArgs e)
    {
        SyncHorizontalScroll(FrozenRowsDataGrid, e.HorizontalOffset, e.HorizontalChange);
    }

    private void FrozenRowsDataGrid_ScrollChanged(object sender, ScrollChangedEventArgs e)
    {
        SyncHorizontalScroll(CsvDataGrid, e.HorizontalOffset, e.HorizontalChange);
    }

    private void RegisterColumnWidthSync()
    {
        var descriptor = DependencyPropertyDescriptor.FromProperty(DataGridColumn.ActualWidthProperty, typeof(DataGridColumn));
        foreach (var column in _widthObservedColumns)
        {
            descriptor.RemoveValueChanged(column, MainColumnWidthChanged);
        }

        _widthObservedColumns.Clear();

        if (CsvDataGrid.Columns.Count == 0 || FrozenRowsDataGrid.Columns.Count == 0)
        {
            return;
        }

        foreach (var column in CsvDataGrid.Columns)
        {
            descriptor.AddValueChanged(column, MainColumnWidthChanged);
            _widthObservedColumns.Add(column);
        }
    }

    private void MainColumnWidthChanged(object? sender, EventArgs e)
    {
        if (_syncingColumnWidths)
        {
            return;
        }

        SyncColumnLayouts(CsvDataGrid, FrozenRowsDataGrid);
    }

    private void QueueColumnLayoutSync()
    {
        Dispatcher.BeginInvoke(() => SyncColumnLayouts(CsvDataGrid, FrozenRowsDataGrid), System.Windows.Threading.DispatcherPriority.Loaded);
    }

    private void ApplySearchHighlightStyles(DataGrid dataGrid)
    {
        if (FindResource("SearchHighlightBrushConverter") is not IMultiValueConverter converter)
        {
            return;
        }

        foreach (var column in dataGrid.Columns.OfType<DataGridTextColumn>())
        {
            var style = new Style(typeof(TextBlock));
            style.Setters.Add(new Setter(TextBlock.PaddingProperty, new Thickness(2, 0, 2, 0)));

            var backgroundBinding = new MultiBinding { Converter = converter };
            backgroundBinding.Bindings.Add(new Binding(column.Binding is Binding binding ? binding.Path?.Path : "")
            {
                Mode = BindingMode.OneWay
            });
            backgroundBinding.Bindings.Add(new Binding("DataContext.SelectedDocument.SearchText")
            {
                RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(Window), 1),
                Mode = BindingMode.OneWay
            });

            style.Setters.Add(new Setter(TextBlock.BackgroundProperty, backgroundBinding));
            column.ElementStyle = style;
        }
    }

    private void SyncHorizontalScroll(DataGrid target, double offset, double change)
    {
        if (_syncingHorizontalScroll || change == 0)
        {
            return;
        }

        var scrollViewer = FindVisualChild<ScrollViewer>(target);
        if (scrollViewer == null)
        {
            return;
        }

        _syncingHorizontalScroll = true;
        scrollViewer.ScrollToHorizontalOffset(offset);
        _syncingHorizontalScroll = false;
    }

    private void SyncColumnLayouts(DataGrid source, DataGrid target)
    {
        if (source.Columns.Count == 0 || target.Columns.Count == 0)
        {
            return;
        }

        _syncingColumnWidths = true;
        var count = Math.Min(source.Columns.Count, target.Columns.Count);
        for (var i = 0; i < count; i++)
        {
            target.Columns[i].DisplayIndex = source.Columns[i].DisplayIndex;
            var actualWidth = source.Columns[i].ActualWidth;
            if (!double.IsNaN(actualWidth) && actualWidth > 0)
            {
                target.Columns[i].Width = new DataGridLength(actualWidth);
            }
        }

        _syncingColumnWidths = false;
    }

    private static T? FindVisualChild<T>(DependencyObject parent) where T : DependencyObject
    {
        for (var i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T typedChild)
            {
                return typedChild;
            }

            var descendant = FindVisualChild<T>(child);
            if (descendant != null)
            {
                return descendant;
            }
        }

        return null;
    }

    private void About_Click(object sender, RoutedEventArgs e)
    {
        MessageBox.Show("CSV Viewer\nWindows CSV 只读阅读器", "关于", MessageBoxButton.OK, MessageBoxImage.Information);
    }

    private void FolderTreeView_ItemExpanded(object sender, RoutedEventArgs e)
    {
        if (e.OriginalSource is TreeViewItem item && item.DataContext is FileTreeNode node)
        {
            if (DataContext is MainViewModel viewModel)
            {
                viewModel.ExpandTreeNode(node);
            }
        }
    }

    private async void FolderTreeView_ItemSelected(object sender, RoutedEventArgs e)
    {
        if (e.OriginalSource is TreeViewItem item && item.DataContext is FileTreeNode node && !node.IsDirectory)
        {
            if (DataContext is MainViewModel viewModel)
            {
                await viewModel.OpenFileNodeAsync(node);
            }
        }
    }

    private async void FileListBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (sender is not ListBox listBox || listBox.SelectedItem is not FileTreeNode node)
        {
            return;
        }

        listBox.SelectedItem = null;
        if (DataContext is MainViewModel viewModel)
        {
            await viewModel.OpenFileNodeAsync(node);
        }
    }

    private void Exit_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
